apiVersion: apps/v1
kind: Deployment
metadata:
  name: kctf-operator
  namespace: kctf-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kctf-operator
  template:
    metadata:
      labels:
        name: kctf-operator
    spec:
      serviceAccountName: kctf-operator
      containers:
        - name: kctf-operator
          # TODO: Replace this with the built image name
          image: gcr.io/kctf-docker/kctf-operator@sha256:b84eba2e3146dc43e986a626762f64533a2ae6b889b0d52aef7866f92197870f
          command:
          - kctf-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kctf-operator"
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/initialized
            initialDelaySeconds: 5
            periodSeconds: 5
